# Generated by Django 4.0.3 on 2022-03-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humiditymodel',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humiditie', to='data.datarecordmodel'),
        ),
        migrations.AlterField(
            model_name='pressuremodel',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure', to='data.datarecordmodel'),
        ),
        migrations.AlterField(
            model_name='temperaturemodel',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='data.datarecordmodel'),
        ),
    ]
