# Generated by Django 4.0.3 on 2022-03-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_humiditymodel_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humiditymodel',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humidity', to='data.datarecordmodel'),
        ),
    ]
