# Generated by Django 4.0.3 on 2022-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_datarecordmodel_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressuremodel',
            name='record',
        ),
        migrations.RemoveField(
            model_name='temperaturemodel',
            name='record',
        ),
        migrations.AlterField(
            model_name='datarecordmodel',
            name='type',
            field=models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity'), ('PRESSURE', 'Pressure')], max_length=11),
        ),
        migrations.DeleteModel(
            name='HumidityModel',
        ),
        migrations.DeleteModel(
            name='PressureModel',
        ),
        migrations.DeleteModel(
            name='TemperatureModel',
        ),
    ]
